/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as LevelTestRouteImport } from './routes/level-test'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as IndexRouteImport } from './routes/index'

const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelTestRoute = LevelTestRouteImport.update({
  id: '/level-test',
  path: '/level-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/level-test': typeof LevelTestRoute
  '/offer': typeof OfferRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap': typeof SitemapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/level-test': typeof LevelTestRoute
  '/offer': typeof OfferRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap': typeof SitemapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/level-test': typeof LevelTestRoute
  '/offer': typeof OfferRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap': typeof SitemapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents'
    | '/level-test'
    | '/offer'
    | '/privacy-policy'
    | '/sitemap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documents'
    | '/level-test'
    | '/offer'
    | '/privacy-policy'
    | '/sitemap'
  id:
    | '__root__'
    | '/'
    | '/documents'
    | '/level-test'
    | '/offer'
    | '/privacy-policy'
    | '/sitemap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentsRoute: typeof DocumentsRoute
  LevelTestRoute: typeof LevelTestRoute
  OfferRoute: typeof OfferRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapRoute: typeof SitemapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level-test': {
      id: '/level-test'
      path: '/level-test'
      fullPath: '/level-test'
      preLoaderRoute: typeof LevelTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentsRoute: DocumentsRoute,
  LevelTestRoute: LevelTestRoute,
  OfferRoute: OfferRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapRoute: SitemapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
